version: "3"

services:
  db:
    image: mariadb:10.3
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: ./.boing/docker/php
    volumes:
      - .:/srv

  redis:
    image: redis:7

volumes:
  db_data:
