version: "3"

services:
  db:
    image: mariadb:10.3
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: ./.boing/docker/php
      args:
        ENABLE_REDIS: 1
        ENABLE_AMQP: 1
        ENABLE_PCOV: 1
    volumes:
      - .:/srv

  web:
    depends_on:
      - php
    build:
      context: ./.boing/docker/nginx/symfony
    volumes:
      - ./public:/srv/public

  redis:
    image: redis:7

  rabbitmq:
    image: rabbitmq:3.12.4-management

  consumer1:
    build:
      context: ./.boing/docker/php
      args:
        ENABLE_REDIS: 1
        ENABLE_AMQP: 1
    volumes:
      - .:/srv
    command: "php -d memory_limit=-1 bin/console messenger:consume async"

volumes:
  db_data:
