services: 
  App\Tests\Mock\HttpMockClientFactory:
    class: App\Tests\Mock\HttpMockClientFactory
    public: true
    
  httpMock:
    class: Symfony\Component\HttpClient\MockHttpClient
    factory: ['App\Tests\Mock\HttpMockClientFactory', 'create']
    public: true

  App\Services\Interfaces\ProviderCallerInterface:
    class: App\Services\ProviderCaller
    public: true
    arguments:
      $httpClient: '@httpMock'
      $urlAdapter: '@App\Services\Interfaces\UrlAdapterInterface'
      $productDataRepository: '@App\Repository\Data\ProductDataRepository'

rondal:
  scrapers: 
    App\Tests\Resources\DummyScraper: dummyprovider 
