name: PHP Stan

on: [push]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: mariadb:10.3
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Vendor install
      #   run: composer install --no-scripts

      # - name: Phpstan
      #   run: php vendor/bin/phpstan analyse src --configuration=phpstan.neon
