name: PHP Stan

on: [push]

env:
  COMPOSE: docker-compose -f docker-compose.ci.yaml

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Pull db images
        run: ${COMPOSE} pull db

      - name: Execute Docker-compose
        run: ${COMPOSE} up -d db

      - name: Vendor install
        run: composer install --no-scripts

      - name: Phpstan
        run: make phpstan
